class ChessBoard {
  #board = [
    [
      {
        color: "black",
        vertically: 0,
        horizontally: 0,
        pieces: "rook",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 0,
        horizontally: 1,
        pieces: "knight",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 0,
        horizontally: 2,
        pieces: "bishop",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 0,
        horizontally: 3,
        pieces: "queen",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 0,
        horizontally: 4,
        pieces: "king",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 0,
        horizontally: 5,
        pieces: "bishop",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 0,
        horizontally: 6,
        pieces: "knight",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 0,
        horizontally: 7,
        pieces: "rook",
        isTouched: false,
      },
    ],
    [
      {
        color: "black",
        vertically: 1,
        horizontally: 0,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 1,
        horizontally: 1,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 1,
        horizontally: 2,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 1,
        horizontally: 3,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 1,
        horizontally: 4,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 1,
        horizontally: 5,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 1,
        horizontally: 6,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "black",
        vertically: 1,
        horizontally: 7,
        pieces: "pawn",
        isTouched: false,
      },
    ],
    [
      {
        color: null,
        vertically: 2,
        horizontally: 0,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 2,
        horizontally: 1,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 2,
        horizontally: 2,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 2,
        horizontally: 3,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 2,
        horizontally: 4,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 2,
        horizontally: 5,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 2,
        horizontally: 6,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 2,
        horizontally: 7,
        pieces: null,
        isTouched: false,
      },
    ],
    [
      {
        color: null,
        vertically: 3,
        horizontally: 0,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 3,
        horizontally: 1,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 3,
        horizontally: 2,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 3,
        horizontally: 3,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 3,
        horizontally: 4,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 3,
        horizontally: 5,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 3,
        horizontally: 6,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 3,
        horizontally: 7,
        pieces: null,
        isTouched: false,
      },
    ],
    [
      {
        color: null,
        vertically: 4,
        horizontally: 0,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 4,
        horizontally: 1,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 4,
        horizontally: 2,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 4,
        horizontally: 3,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 4,
        horizontally: 4,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 4,
        horizontally: 5,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 4,
        horizontally: 6,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 4,
        horizontally: 7,
        pieces: null,
        isTouched: false,
      },
    ],
    [
      {
        color: null,
        vertically: 5,
        horizontally: 0,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 5,
        horizontally: 1,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 5,
        horizontally: 2,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 5,
        horizontally: 3,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 5,
        horizontally: 4,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 5,
        horizontally: 5,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 5,
        horizontally: 6,
        pieces: null,
        isTouched: false,
      },
      {
        color: null,
        vertically: 5,
        horizontally: 7,
        pieces: null,
        isTouched: false,
      },
    ],
    [
      {
        color: "white",
        vertically: 6,
        horizontally: 0,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 6,
        horizontally: 1,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 6,
        horizontally: 2,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 6,
        horizontally: 3,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 6,
        horizontally: 4,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 6,
        horizontally: 5,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 6,
        horizontally: 6,
        pieces: "pawn",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 6,
        horizontally: 7,
        pieces: "pawn",
        isTouched: false,
      },
    ],
    [
      {
        color: "white",
        vertically: 7,
        horizontally: 0,
        pieces: "rook",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 7,
        horizontally: 1,
        pieces: "knight",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 7,
        horizontally: 2,
        pieces: "bishop",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 7,
        horizontally: 3,
        pieces: "queen",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 7,
        horizontally: 4,
        pieces: "king",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 7,
        horizontally: 5,
        pieces: "bishop",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 7,
        horizontally: 6,
        pieces: "knight",
        isTouched: false,
      },
      {
        color: "white",
        vertically: 7,
        horizontally: 7,
        pieces: "rook",
        isTouched: false,
      },
    ],
  ];
  #enPassant = {
    black: { vertically: null, horizontally: null },
    white: { vertically: null, horizontally: null },
  };
  #kingsPossition = {
    black: { vertically: 0, horizontally: 4, check: false },
    white: { vertically: 7, horizontally: 4, check: false },
  };
  #globalColor = 'white';
  constructor() {}
};

export default ChessBoard;